name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Bucket 80
      id: bucket-80
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 80
        setup-command: sh ./config_test.sh bucket_80
    - name: Bucket 100
      id: bucket-100
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: sh ./config_test.sh bucket_100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUCKET-80_RESULTS: "${{steps.bucket-80.outputs.result}}"
        BUCKET-100_RESULTS: "${{steps.bucket-100.outputs.result}}"
      with:
        runners: bucket-80,bucket-100
